[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "definitions"
code_location_name = "lessons_dagster"
working_directory = "lessons_dagster/lessons_dagster"
