lessons:
  outputs:
    dev:
      dataset: dbt_jack
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: carbide-algebra-269412
      threads: 60
      type: bigquery
  target: dev
