answers:
  outputs:
    dev:
      dataset: dbt_mateusz
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: level-slate-452111-p7
      threads: 60
      type: bigquery
  target: dev
